### ISSUE TITLE
fetch_json() in refresh_token() should also be rate limited

### ISSUE THREAD

**Issue by griskot** [banteg/rarbg#12]
This block of code in `api()`

    async with app.lock:
        await refresh_token()
        params.update(token=app.token, format='json_extended', app_id=APP_ID)
        data = await fetch_json(API_ENDPOINT, params=params)
        await asyncio.sleep(API_RATE_LIMIT)

Results in 2 `fetch_json()` in a row (one inside `refresh_token()`) and causes rarbg's web server to return http error 429 (Too Many Requests) sometimes.  Then `resp.json()` in the second `fetch_json()` will cause an exception because the response is invalid.

The `fetch_json()` in `refresh_token()` should be rate-limited like the other one to avoid this.

I added this line

    await asyncio.sleep(API_RATE_LIMIT)

Before `click.secho()` in `refresh_token()` and it seemed to prevent the exception.  Please review if it is correct.

Possibly, some checking in `fetch_json()` to make sure `app.s.get()` succeeded before using the response can be done, to make the code more robust.

**Comment by banteg** [comment]
I've changed the logic a bit, let me know if the change helps.

**Comment by griskot** [comment]
Thanks for the quick response.  Ran 1.1.6 for half a day so far, it is working fine for me, did not get any Bad Response or exception.
