### ISSUE TITLE
Escaped URLS

### ISSUE THREAD

**Issue by angramainyu74** [banteg/rarbg#2]
Not sure about other clients, but to get qBittorrent to be able to parse the feed, I had to change

url="{{entry.download}}"
to 
url="{{entry.download|e}}"

-- there was an unescaped ampersand in the URL that was causing qBittorrent's parser to fail.  Other fields might also have issues, perhaps escape them all?

**Comment by angramainyu74** [comment]
One other fix I needed for qBittorrent to work:  I had to remove the blank line before the opening <?xml tag.

**Comment by banteg** [comment]
Greatly appreciate your help. Thanks!
