### ISSUE TITLE
Little help in sorting

### ISSUE THREAD

**Issue by taigalover** [banteg/rarbg#3]
I want it to sort it by earliest releases of steven universe and limit it by 100

I got the limiting part : http://rarbgrss.tk/search/steven universe&?limit=100

But i just need a little help in entering the date sort.

Help is appreciated. 

Edit: Not sure if there is even a date sort, but if there isnt then its fine.

**Comment by banteg** [comment]
It's sorted by date in reverse chronological order by default. If you want the results sorted by episode release date, I'm afraid that can't be done as it's not implemented in the API. You can try [Sonarr](https://sonarr.tv), it's a much more advanced tool.
